# Generated by Django 2.0.5 on 2019-12-20 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='activa',
            new_name='active',
        ),
    ]
